### ISSUE TITLE
؟

### ISSUE THREAD

**Issue by 66Hamidreza** [wizwizdev/script-panel#1]
سلام 
این سرویس برای بکاپ از کانفیگ سرور ها و ارسال به ربات تلگرام هست؟
اگر بله پس برای سرور های تانل کاربرد نداره چون تلگرام کار نمیکنه روشون

**Comment by wizwizdev** [comment]
سلام شما کاری به سرور تانل ندارید ، میرید روی سرور اصلی ران میکنید بک اپ توی سرور اصلی هست که خارجه
برای همه میشه
