### ISSUE TITLE
تنظیمات

### ISSUE THREAD

**Issue by davoodr22** [wizwizdev/script-panel#3]
دستوری برای ویرایش تنظیمات و یا اطلاعات وارد شده وجود نداره؟ مجدد باید نصب کنیم اسکریپت رو؟
حذفش به چه صورته؟

**Comment by wizwizdev** [comment]
تنظیمات چی؟ کامل توضیح بدید

**Comment by wizwizdev** [comment]
اها منظورتون اینه اطلاعات قبلی پاک کنید از اول وارد کنید؟

**Comment by davoodr22** [comment]
بله 
من اسکریپت رو نصب کردم میخوام ویرایش کنم قسمت توکن و سیکل ارسال بک اپ رو
و همچنین روی یه سرور دیگه به اشتباه نصب کردم میخوام پاکش کنم از روی اون حالا

**Comment by wizwizdev** [comment]
یکی دو روز دیگ بخش ریست اضافه میشه

**Comment by davoodr22** [comment]
ممنون
از کانال پیگیری میکنم پس 
و اینکه اگه مقدوره براتون یه قابلیتی اضافه کنید بک اپ جدید میگیره بیاد بک اپ قبلی رو پاک کنه
مسیر ذخیره بک اپ های فعلی کجاس دقیقا الان؟

**Comment by wizwizdev** [comment]
بک اپ نمیگیره ، مستقیم بک اپ رو میفرسته همشون به تاریخ جدیدن
