### ISSUE TITLE
بکاپ برای سرور ایران

### ISSUE THREAD

**Issue by mohammad1937** [wizwizdev/script-panel#4]
من x-ui روی سرور ایران نصب کردم. چون تلگرام فیلتره نمیتونه فایل بکاپ رو بفرسته. نمیشه مثل ربات ویزویز از طریق ربات وارد پنل شد و از اونجا فایل بکاپ گرفته بشه؟

**Comment by wizwizdev** [comment]
خیر متاسفانه نمیشه
